apiVersion: batch/v1beta1
kind: CronJob
metadata:
    name: cronjob
spec:
    schedule: "0,15,30,40 * * * *"
    startingDeadlineSeconds: 15
    jobTemplate:
        spec:
            template:
                metadata:
                    labels:
                        app: cronjob
                spec:
                    restartPolicy: OnFailure
                    containers:
                        - name: main
                          image: luksa/batch-job
