apiVersion: v1
kind: Pod
metadata:
    name: kubia-manual-v3
    labels:
        creation_method: manual
        env: prod
spec:
    nodeSelector:
        capable: "true"
    containers:
        - image: luksa/kubia
          name: kubia
          ports:
              - containerPort: 8080
                protocol: TCP
