apiVersion: v1
kind: Pod
metadata:
    name: kubia-manual-v3-liveness
    labels:
        creation_method: manual
        env: prod
spec:
    nodeSelector:
        capable: "true"
    containers:
        - image: luksa/kubia-unhealthy
          name: kubia
          livenessProbe:
              initialDelaySeconds: 15
              httpGet:
                  path: /
                  port: 8080


          ports:
              - containerPort: 8080
                protocol: TCP
